name: IPTV简易测速采集
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: python collect.py
      - name: 提交文件
        run: |
          git config user.name "bot"
          git config user.email "bot@run.com"
          git add .
          git commit -m "update iptv" || true
          git push
