name: IPTV Auto API Update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          pip install playwright flask
          playwright install

      - name: Run Sniffer
        env:
          AISIMU_USER: ${{ secrets.AISIMU_USER }}
          AISIMU_PASS: ${{ secrets.AISIMU_PASS }}
        run: |
          python v5_sniffer.py

      - name: Commit data
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"

          git add streams.json
          git commit -m "update IPTV API data" || echo "no change"
          git push
